const colleges =[
    {
        name: "MIT",
        SATmath: "790-800",
        SATenglish: "730-780",
        ACTcomposite: "35-36",
        GPA: "4.0+",
        AcceptanceRate: "4.1%",
        img: "https://download.logo.wine/logo/Massachusetts_Institute_of_Technology/Massachusetts_Institute_of_Technology-Logo.wine.png",
    },
    {
        name: "Harvard University",
        SATmath: "750-800",
        SATenglish: "730-780",
        ACTcomposite: "33-36",
        GPA: "4.0+",
        AcceptanceRate: "4%",
        img: "https://1000logos.net/wp-content/uploads/2017/02/Harvard-Logo.png",
    },
    {
        name: "Northeastern University",
        SATmath: "730-790",
        SATenglish: "700-760",
        ACTcomposite: "33-35",
        GPA: "4.0+",
        AcceptanceRate: "18.4%",
        img:"https://logos-download.com/wp-content/uploads/2019/06/Northeastern_University_Logo_full.png",
    },
    {
        name: "Boston University",
        SATmath: "700-780",
        SATenglish: "660-740",
        ACTcomposite: "31-34",
        GPA: "4.0+",
        AcceptanceRate: "18.6%",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Boston_University_wordmark.svg/1200px-Boston_University_wordmark.svg.png",
    },
    {
        name: "Yale",
        SATmath: "750-800",
        SATenglish: "730-780",
        ACTcomposite: "33-35",
        GPA: "4.0+",
        AcceptanceRate: "5.3%",
        img: "https://logos-world.net/wp-content/uploads/2021/11/Yale-Bulldogs-Logo-1997-2019.png",
    },
    {
        name: "Columbia",
        SATmath: "740-800",
        SATenglish: "720-770",
        ACTcomposite: "33-35",
        GPA: "4.0+",
        AcceptanceRate: "4.4%",
        img: "https://assets.stickpng.com/images/62796e6c53c8a73e766a78e2.png",
    },
    {
        name: "New York University",
        SATmath: "750-800",
        SATenglish: "700-770",
        ACTcomposite: "32-35",
        GPA: "4.0+",
        AcceptanceRate: "13%",
        img: "https://logos-world.net/wp-content/uploads/2021/09/NYU-Logo.png",
    },
    {
        name: "Georgia Tech",
        SATmath: "630-730",
        SATenglish: "630-730",
        ACTcomposite: "30-34",
        GPA: "4.0+",
        AcceptanceRate: "16%",
        img: "https://logos-world.net/wp-content/uploads/2021/08/Georgia-Tech-Emblem.png",
    },
    {
        name: "Cornell",
        SATmath: "750-800",
        SATenglish: "700-760",
        ACTcomposite: "33-35",
        GPA: "4.0+",
        AcceptanceRate: "8.7%",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Cornell_University_seal.svg/2048px-Cornell_University_seal.svg.png",
    },
    
]
